name: Deployment

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install yarn
      run: |
        npm install yarn -g
    - name: Build
      run: |
        yarn install
        yarn prod
    - name: Deploy
      run: |
        git config --global user.email "liyu@betterliyu.site"
        git config --global user.name "betterliyu" 
        mkdir ./publish 
        cd ./publish
        git init 
        git remote add origin https://betterliyu:${{ secrets.ACCESS_TOKEN }}@github.com/betterliyu/betterliyu.github.io.git
        git fetch origin
        git checkout -b master origin/master
        find . | grep -v .git | xargs rm -rf
        ls -a
        cd ..
        cp -r /dist/. /publish
        ls -a /publish
        
