name: Deployment

on:
  pull_request:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build
        run: |
          npm install yarn -g
          yarn install
          yarn prod
      - name: Deploy
        run: |
          git show -s
          author=$(git show -s --format=%aN)
          email=$(git show -s --format=%aE)
          repo="https://betterliyu:${{ secrets.ACCESS_TOKEN }}@github.com/betterliyu/betterliyu.github.io.git"
          branch="master"
          cname="www.betterliyu.site"
          chmod u+r+x .deploy.sh
          ./.deploy.sh $author $email $repo $branch $cname 
